//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SselphGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-add_not_found=false")]
        public string add_not_found {
            get {
                return ((string)(this["add_not_found"]));
            }
            set {
                this["add_not_found"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-append=false")]
        public string append {
            get {
                return ((string)(this["append"]));
            }
            set {
                this["append"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-console_img=b")]
        public string console_img {
            get {
                return ((string)(this["console_img"]));
            }
            set {
                this["console_img"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-console_src=gdb")]
        public string console_src {
            get {
                return ((string)(this["console_src"]));
            }
            set {
                this["console_src"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-convert_videos=false")]
        public string convert_videos {
            get {
                return ((string)(this["convert_videos"]));
            }
            set {
                this["convert_videos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-download_images=true")]
        public string download_images {
            get {
                return ((string)(this["download_images"]));
            }
            set {
                this["download_images"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-download_marquees=false")]
        public string download_marquees {
            get {
                return ((string)(this["download_marquees"]));
            }
            set {
                this["download_marquees"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-download_videos=false")]
        public string download_videos {
            get {
                return ((string)(this["download_videos"]));
            }
            set {
                this["download_videos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-extra_ext=")]
        public string extra_ext {
            get {
                return ((string)(this["extra_ext"]));
            }
            set {
                this["extra_ext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string image_dir {
            get {
                return ((string)(this["image_dir"]));
            }
            set {
                this["image_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-image_path=images")]
        public string image_path {
            get {
                return ((string)(this["image_path"]));
            }
            set {
                this["image_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-image_suffix=-image")]
        public string image_suffix {
            get {
                return ((string)(this["image_suffix"]));
            }
            set {
                this["image_suffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-img_format=jpg")]
        public string img_format {
            get {
                return ((string)(this["img_format"]));
            }
            set {
                this["img_format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-img_workers=0")]
        public string img_workers {
            get {
                return ((string)(this["img_workers"]));
            }
            set {
                this["img_workers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-lang=en")]
        public string lang {
            get {
                return ((string)(this["lang"]));
            }
            set {
                this["lang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-mame=false")]
        public string mame {
            get {
                return ((string)(this["mame"]));
            }
            set {
                this["mame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-mame_img=t,m,s,c")]
        public string mame_img {
            get {
                return ((string)(this["mame_img"]));
            }
            set {
                this["mame_img"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-mame_src=adb,gdb")]
        public string mame_src {
            get {
                return ((string)(this["mame_src"]));
            }
            set {
                this["mame_src"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string marquee_dir {
            get {
                return ((string)(this["marquee_dir"]));
            }
            set {
                this["marquee_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-marquee_format=png")]
        public string marquee_format {
            get {
                return ((string)(this["marquee_format"]));
            }
            set {
                this["marquee_format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-marquee_path=images")]
        public string marquee_path {
            get {
                return ((string)(this["marquee_path"]));
            }
            set {
                this["marquee_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-marquee_suffix=-marquee")]
        public string marquee_suffix {
            get {
                return ((string)(this["marquee_suffix"]));
            }
            set {
                this["marquee_suffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string max_height {
            get {
                return ((string)(this["max_height"]));
            }
            set {
                this["max_height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-max_width=400")]
        public string max_width {
            get {
                return ((string)(this["max_width"]));
            }
            set {
                this["max_width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string missing {
            get {
                return ((string)(this["missing"]));
            }
            set {
                this["missing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-nested_img_dir=false")]
        public string nested_img_dir {
            get {
                return ((string)(this["nested_img_dir"]));
            }
            set {
                this["nested_img_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-no_thumb")]
        public string no_thumb {
            get {
                return ((string)(this["no_thumb"]));
            }
            set {
                this["no_thumb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string output_file {
            get {
                return ((string)(this["output_file"]));
            }
            set {
                this["output_file"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string overview_len {
            get {
                return ((string)(this["overview_len"]));
            }
            set {
                this["overview_len"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-region=us,wor,eu,jp,fr,xx")]
        public string region {
            get {
                return ((string)(this["region"]));
            }
            set {
                this["region"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-retries=2")]
        public string retries {
            get {
                return ((string)(this["retries"]));
            }
            set {
                this["retries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string rom_dir {
            get {
                return ((string)(this["rom_dir"]));
            }
            set {
                this["rom_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-rom_path=.")]
        public string rom_path {
            get {
                return ((string)(this["rom_path"]));
            }
            set {
                this["rom_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-skip_check=true")]
        public string skip_check {
            get {
                return ((string)(this["skip_check"]));
            }
            set {
                this["skip_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-ss_password=")]
        public string ss_password {
            get {
                return ((string)(this["ss_password"]));
            }
            set {
                this["ss_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-ss_user=")]
        public string ss_user {
            get {
                return ((string)(this["ss_user"]));
            }
            set {
                this["ss_user"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-strip_unicode=false")]
        public string strip_unicode {
            get {
                return ((string)(this["strip_unicode"]));
            }
            set {
                this["strip_unicode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-update_cache=true")]
        public string update_cache {
            get {
                return ((string)(this["update_cache"]));
            }
            set {
                this["update_cache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-use_filename=false")]
        public string use_filename {
            get {
                return ((string)(this["use_filename"]));
            }
            set {
                this["use_filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-use_nointro_name=true")]
        public string use_nointro_name {
            get {
                return ((string)(this["use_nointro_name"]));
            }
            set {
                this["use_nointro_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string video_dir {
            get {
                return ((string)(this["video_dir"]));
            }
            set {
                this["video_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-video_path=images")]
        public string video_path {
            get {
                return ((string)(this["video_path"]));
            }
            set {
                this["video_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-video_suffix=-video")]
        public string video_suffix {
            get {
                return ((string)(this["video_suffix"]));
            }
            set {
                this["video_suffix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-workers=1")]
        public string workers {
            get {
                return ((string)(this["workers"]));
            }
            set {
                this["workers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("images")]
        public string image_path_string {
            get {
                return ((string)(this["image_path_string"]));
            }
            set {
                this["image_path_string"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("images")]
        public string marquee_path_string {
            get {
                return ((string)(this["marquee_path_string"]));
            }
            set {
                this["marquee_path_string"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("images")]
        public string video_path_string {
            get {
                return ((string)(this["video_path_string"]));
            }
            set {
                this["video_path_string"] = value;
            }
        }
    }
}
